# Project Ground Truth
<!-- Auto-generated by Persistence CLI — DO NOT EDIT MANUALLY -->
<!-- Last scan: 2026-03-30 05:36:22 UTC -->

## Tech Stack



## Environment Variables

_Source: .env.example_

ARIBA_REALM, ARIBA_CLIENT_ID, ARIBA_CLIENT_SECRET, ARIBA_API_KEY


## Project Structure

```
src/
  ariba_mcp/ (17 files)
    models/ (2 files)
      __init__.py
      common.py
    tools/ (9 files)
      __init__.py
      analytical_reporting.py
      contract_compliance.py
      document_approval.py
      operational_procurement.py
      operational_sourcing.py
      sourcing_project.py
      supplier_data.py
      supplier_risk.py
    __init__.py
    auth.py
    client.py
    config.py
    errors.py
    server.py
```
