import json

from fastmcp import FastMCP

from ariba_mcp.client import AribaClient
from ariba_mcp.errors import handle_ariba_error

SURROGATE_BID_API = "sourcing-event-bid/v1/prod"


def register(mcp: FastMCP, client: AribaClient) -> None:

    @mcp.tool(
        name="ariba_surrogate_bid_export",
        description=(
            "Step 1 of surrogate bidding: create an export job that generates a bid-response "
            "sheet (Excel) for a specific participant (supplier) in an SAP Ariba Sourcing event. "
            "Returns a jobId that must be polled with ariba_surrogate_bid_job_status until "
            "the status is 'Success', after which the sheet can be downloaded with "
            "ariba_surrogate_bid_download_file."
        ),
        annotations={
            "readOnlyHint": False,
            "destructiveHint": False,
            "idempotentHint": False,
            "openWorldHint": True,
        },
    )
    async def surrogate_bid_export(
        realm: str,
        event_id: str,
        participant_id: str,
        user: str,
        password_adapter: str,
    ) -> str:
        try:
            params = {
                "user": user,
                "passwordAdapter": password_adapter,
                "realm": realm,
            }
            payload = {
                "operation": "export",
                "eventId": event_id,
                "participantId": participant_id,
            }
            result = await client.post_resource(
                SURROGATE_BID_API, "jobs", params=params, json_body=payload
            )
            return json.dumps(result, default=str)
        except Exception as e:
            return handle_ariba_error(e)

    @mcp.tool(
        name="ariba_surrogate_bid_job_status",
        description=(
            "Poll the status of an SAP Ariba Surrogate Bid job (export, import, or submit). "
            "Call repeatedly until the returned status is 'Success' or 'Failed'. "
            "On success of an export job the response also contains the fileId needed to "
            "download the bid-response sheet."
        ),
        annotations={
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": True,
        },
    )
    async def surrogate_bid_job_status(
        realm: str,
        job_id: str,
        user: str,
        password_adapter: str,
    ) -> str:
        try:
            params = {
                "user": user,
                "passwordAdapter": password_adapter,
                "realm": realm,
            }
            result = await client.fetch_resource(
                SURROGATE_BID_API, f"jobs/{job_id}", params
            )
            return json.dumps(result, default=str)
        except Exception as e:
            return handle_ariba_error(e)

    @mcp.tool(
        name="ariba_surrogate_bid_download_file",
        description=(
            "Step 3 of surrogate bidding: download the bid-response Excel sheet that was "
            "generated by a successful export job. The fileId is obtained from the job-status "
            "response. The returned bytes should be saved as an .xlsx file, filled in with "
            "bid values, and then base64-encoded for the import step."
        ),
        annotations={
            "readOnlyHint": True,
            "destructiveHint": False,
            "idempotentHint": True,
            "openWorldHint": True,
        },
    )
    async def surrogate_bid_download_file(
        realm: str,
        job_id: str,
        file_id: str,
        user: str,
        password_adapter: str,
    ) -> str:
        try:
            params = {
                "user": user,
                "passwordAdapter": password_adapter,
                "realm": realm,
            }
            result = await client.fetch_resource(
                SURROGATE_BID_API, f"jobs/{job_id}/files/{file_id}", params
            )
            return json.dumps(result, default=str)
        except Exception as e:
            return handle_ariba_error(e)

    @mcp.tool(
        name="ariba_surrogate_bid_import",
        description=(
            "Step 4 of surrogate bidding: upload a completed bid-response Excel sheet "
            "(base64-encoded) back to SAP Ariba. This creates an import job whose status "
            "must be polled with ariba_surrogate_bid_job_status until 'Success'. "
            "After a successful import, call ariba_surrogate_bid_submit to finalise the bid."
        ),
        annotations={
            "readOnlyHint": False,
            "destructiveHint": False,
            "idempotentHint": False,
            "openWorldHint": True,
        },
    )
    async def surrogate_bid_import(
        realm: str,
        event_id: str,
        participant_id: str,
        user: str,
        password_adapter: str,
        file_base64: str,
        file_name: str = "bid_response.xlsx",
    ) -> str:
        try:
            params = {
                "user": user,
                "passwordAdapter": password_adapter,
                "realm": realm,
            }
            payload = {
                "operation": "import",
                "eventId": event_id,
                "participantId": participant_id,
                "fileName": file_name,
                "fileContent": file_base64,
            }
            result = await client.post_resource(
                SURROGATE_BID_API, "jobs", params=params, json_body=payload
            )
            return json.dumps(result, default=str)
        except Exception as e:
            return handle_ariba_error(e)

    @mcp.tool(
        name="ariba_surrogate_bid_submit",
        description=(
            "Step 5 of surrogate bidding: submit the imported bid on behalf of a participant "
            "in an SAP Ariba Sourcing event. Must be called after a successful import job. "
            "Creates a submit job whose status should be polled with "
            "ariba_surrogate_bid_job_status until 'Success'. "
            "WARNING: Do not use this tool and the SAP Ariba interactive UI to bid on the "
            "same event and participant at the same time – concurrent operations can cause "
            "bids to need resubmission."
        ),
        annotations={
            "readOnlyHint": False,
            "destructiveHint": False,
            "idempotentHint": False,
            "openWorldHint": True,
        },
    )
    async def surrogate_bid_submit(
        realm: str,
        event_id: str,
        participant_id: str,
        user: str,
        password_adapter: str,
    ) -> str:
        try:
            params = {
                "user": user,
                "passwordAdapter": password_adapter,
                "realm": realm,
            }
            payload = {
                "operation": "submit",
                "eventId": event_id,
                "participantId": participant_id,
            }
            result = await client.post_resource(
                SURROGATE_BID_API, "jobs", params=params, json_body=payload
            )
            return json.dumps(result, default=str)
        except Exception as e:
            return handle_ariba_error(e)
